export const works = [
  {
    id: 1,
    title: "Neon Genesis",
    author: "Crypto Artisan",
    image: "/cyberpunk-neon-art.jpg",
    images: ["/cyberpunk-neon-art.jpg", "/abstract-fabric-pattern.png", "/holographic-glass-sculpture.jpg"],
    story: "A vision of a future where neon lights replace the stars, guiding lost souls through the digital ether.",
    material: "Digital, Light, Code",
    likes: 124,
    tags: ["digital", "cyberpunk"],
    allowRemix: true,
    remixCount: 12,
    remixers: ["Alice", "Bob", "Charlie", "Dave"],
    collectionStatus: "none", // none, pending, approved, rejected
    savedAt: null,
    savedFolder: null,
    createdAt: "2023-11-15",
  },
  {
    id: 2,
    title: "Ethereal Pottery",
    author: "Elena Crafts",
    image: "/ceramic-pottery-artistic.jpg",
    images: ["/ceramic-pottery-artistic.jpg", "/organic-wood-carving.jpg"],
    story: "Molded from the earth of the ancient riverbeds, fired in kilns whispering with old spirits.",
    material: "Clay, Glaze, Fire",
    likes: 89,
    tags: ["ceramic", "minimalist"],
    allowRemix: false, // No remix allowed
    remixCount: 5,
    remixers: ["Eve", "Frank"],
    collectionStatus: "none",
    savedAt: null,
    savedFolder: null,
    createdAt: "2023-12-10",
  },
  {
    id: 3,
    title: "Quantum Weave",
    author: "Textile Dreams",
    image: "/abstract-fabric-pattern.png",
    images: ["/abstract-fabric-pattern.png", "/glitch-art-tapestry.jpg"],
    story: "Threads that bind the fabric of reality, interwoven with quantum entanglements.",
    material: "Silk, Nanofiber",
    likes: 256,
    tags: ["fabric", "pattern"],
    allowRemix: true,
    remixCount: 34,
    remixers: ["Grace", "Heidi", "Ivan", "Judy", "Mallory"],
    collectionStatus: "approved",
    savedAt: "2024-07-01 18:45",
    savedFolder: "To Remix",
    createdAt: "2024-01-05",
  },
  {
    id: 4,
    title: "Holographic Glass",
    author: "Glass Master",
    image: "/holographic-glass-sculpture.jpg",
    images: ["/holographic-glass-sculpture.jpg"],
    story: "Reflecting light from dimensions unseen.",
    material: "Glass, Hologram",
    likes: 45,
    tags: ["glass", "modern"],
    allowRemix: true,
    remixCount: 2,
    remixers: ["Niaj", "Olivia"],
    collectionStatus: "pending",
    savedAt: "2024-08-10 11:20",
    savedFolder: "Inspiration",
    createdAt: "2024-02-14",
  },
  {
    id: 5,
    title: "Cyber Metal",
    author: "Iron Age",
    image: "/futuristic-metal-sculpture.jpg",
    images: ["/futuristic-metal-sculpture.jpg"],
    story: "Forged in the heart of a dying star.",
    material: "Steel, Neon",
    likes: 112,
    tags: ["metal", "abstract"],
    allowRemix: false,
    remixCount: 8,
    remixers: ["Peggy", "Rupert"],
    collectionStatus: "none",
    savedAt: "2024-09-05 16:00",
    savedFolder: "Research",
    createdAt: "2024-03-01",
  },
  {
    id: 6,
    title: "Neural Woodwork",
    author: "Bio Carver",
    image: "/organic-wood-carving.jpg",
    images: ["/organic-wood-carving.jpg"],
    story: "Wood that remembers the forest it came from.",
    material: "Oak, Varnish",
    likes: 67,
    tags: ["wood", "bio-design"],
    allowRemix: true,
    remixCount: 15,
    remixers: ["Sybil", "Ted", "Walter"],
    collectionStatus: "none",
    savedAt: null,
    savedFolder: null,
    createdAt: "2024-03-15",
  },
  {
    id: 7,
    title: "Glitch Tapestry",
    author: "Pixel Weaver",
    image: "/glitch-art-tapestry.jpg",
    images: ["/glitch-art-tapestry.jpg"],
    story: "When the loom encounters a system error.",
    material: "Wool, Pixels",
    likes: 198,
    tags: ["textile", "glitch"],
    allowRemix: true,
    remixCount: 22,
    remixers: ["Zoe", "Yvonne"],
    collectionStatus: "none",
    savedAt: null,
    savedFolder: null,
    createdAt: "2024-04-01",
  },
  {
    id: 8,
    title: "Void Sculpture",
    author: "Dark Matter",
    image: "/black-abstract-sculpture.jpg",
    images: ["/black-abstract-sculpture.jpg"],
    story: "Giving form to the nothingness.",
    material: "Vantablack, Resin",
    likes: 342,
    tags: ["sculpture", "void"],
    allowRemix: true,
    remixCount: 45,
    remixers: ["Xavier", "William", "Victor"],
    collectionStatus: "none",
    savedAt: null,
    savedFolder: null,
    createdAt: "2024-04-10",
  },
  {
    id: 9,
    title: "Digital Horizon",
    author: "Cyber Scape",
    image: "/abstract-digital-landscape.png",
    images: ["/abstract-digital-landscape.png"],
    story: "Where the digital sun never sets.",
    material: "Pixels, Code",
    likes: 156,
    tags: ["digital", "landscape"],
    allowRemix: true,
    remixCount: 10,
    remixers: ["Aiden", "Bella"],
    collectionStatus: "none",
    savedAt: null,
    savedFolder: null,
    createdAt: "2024-04-20",
  },
  {
    id: 10,
    title: "Geometric Dreams",
    author: "Shape Shifter",
    image: "/abstract-geometric.png",
    images: ["/abstract-geometric.png"],
    story: "The building blocks of a new reality.",
    material: "3D Render",
    likes: 210,
    tags: ["abstract", "3d"],
    allowRemix: true,
    remixCount: 18,
    remixers: ["Chris", "Diana"],
    collectionStatus: "none",
    savedAt: null,
    savedFolder: null,
    createdAt: "2024-05-01",
  },
  {
    id: 11,
    title: "Rustic Vase",
    author: "Clay Master",
    image: "/handcrafted-pottery.jpg",
    images: ["/handcrafted-pottery.jpg"],
    story: "Handcrafted with love and patience.",
    material: "Clay, Glaze",
    likes: 78,
    tags: ["pottery", "craft"],
    allowRemix: false,
    remixCount: 0,
    remixers: [],
    collectionStatus: "none",
    savedAt: "2024-10-12 09:30",
    savedFolder: "Favorites",
    createdAt: "2024-05-05",
  },
  {
    id: 12,
    title: "Ancient Weave",
    author: "Loom Legend",
    image: "/woven-tapestry.jpg",
    images: ["/woven-tapestry.jpg"],
    story: "Stories told through threads.",
    material: "Wool, Cotton",
    likes: 134,
    tags: ["textile", "weaving"],
    allowRemix: true,
    remixCount: 25,
    remixers: ["Elena", "Fiona"],
    collectionStatus: "none",
    savedAt: null,
    savedFolder: null,
    createdAt: "2024-05-10",
  },
  {
    id: 13,
    title: "Cyber Implant",
    author: "Tech Surgeon",
    image: "/cybernetic-implant.jpg",
    images: ["/cybernetic-implant.jpg"],
    story: "Enhancing the human form.",
    material: "Metal, Circuitry",
    likes: 312,
    tags: ["cyberpunk", "tech"],
    allowRemix: true,
    remixCount: 40,
    remixers: ["George", "Hannah"],
    collectionStatus: "none",
    savedAt: null,
    savedFolder: null,
    createdAt: "2024-05-15",
  },
  {
    id: 14,
    title: "Glass Swirl",
    author: "Molten Art",
    image: "/glass-blown-art.jpg",
    images: ["/glass-blown-art.jpg"],
    story: "Frozen motion in glass.",
    material: "Glass",
    likes: 95,
    tags: ["glass", "art"],
    allowRemix: true,
    remixCount: 7,
    remixers: ["Ian", "Jack"],
    collectionStatus: "none",
    savedAt: null,
    savedFolder: null,
    createdAt: "2024-05-20",
  },
  {
    id: 15,
    title: "Tribal Mask",
    author: "Wood Spirit",
    image: "/wooden-mask.jpg",
    images: ["/wooden-mask.jpg"],
    story: "A face from the past.",
    material: "Wood, Paint",
    likes: 145,
    tags: ["wood", "tribal"],
    allowRemix: false,
    remixCount: 0,
    remixers: [],
    collectionStatus: "none",
    savedAt: "2024-10-20 14:00",
    savedFolder: "Inspiration",
    createdAt: "2024-05-25",
  },
  {
    id: 16,
    title: "Glowing Flora",
    author: "Bio Hacker",
    image: "/bioluminescent-plant.jpg",
    images: ["/bioluminescent-plant.jpg"],
    story: "Nature enhanced by science.",
    material: "Organic, Bioluminescence",
    likes: 278,
    tags: ["nature", "scifi"],
    allowRemix: true,
    remixCount: 30,
    remixers: ["Kyle", "Liam"],
    collectionStatus: "none",
    savedAt: null,
    savedFolder: null,
    createdAt: "2024-05-30",
  },
  {
    id: 17,
    title: "Motion Machine",
    author: "Gear Head",
    image: "/kinetic-sculpture.jpg",
    images: ["/kinetic-sculpture.jpg"],
    story: "Art in constant motion.",
    material: "Metal, Gears",
    likes: 189,
    tags: ["sculpture", "kinetic"],
    allowRemix: true,
    remixCount: 14,
    remixers: ["Mia", "Noah"],
    collectionStatus: "none",
    savedAt: null,
    savedFolder: null,
    createdAt: "2024-06-01",
  },
  {
    id: 18,
    title: "Virtual Realm",
    author: "VR Architect",
    image: "/vr-environment.jpg",
    images: ["/vr-environment.jpg"],
    story: "A world within a machine.",
    material: "Code, VR",
    likes: 220,
    tags: ["vr", "digital"],
    allowRemix: true,
    remixCount: 28,
    remixers: ["Oscar", "Paul"],
    collectionStatus: "none",
    savedAt: null,
    savedFolder: null,
    createdAt: "2024-06-05",
  },
]
